# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enable entities light source.
	entities = true
	# Enable first-person player light source.
	self = true
	# Enable block entities light source.
	block_entities = true
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				glow_item_frame = false
				player = true
				bat = true
				zombie = true
				creeper = true
				skeleton = true
				cow = true
				sheep = true
				glow_squid = true
				salmon = true
				spider = true
				squid = true
				chicken = true
				cod = true
				enderman = true
				pig = true
				bee = true
				wolf = true
				drowned = true
				item = true
				snowball = true
				boat = true
				zombie_villager = true
				witch = true
				turtle = true
				fox = true
				cave_spider = true
				axolotl = true
				villager = true
				frog = true
				cat = true
				iron_golem = true
				horse = true
				dolphin = true
				tropical_fish = true
				tnt_minecart = true
				chest_minecart = true
				lightning_bolt = true
				slime = true
				experience_orb = true
				pufferfish = true
				donkey = true
				llama = true
				item_frame = true
				rabbit = true
				polar_bear = true
				stray = true
				skeleton_horse = true
				arrow = true
				goat = true
				ravager = true
				armor_stand = true
				pillager = true
				elder_guardian = true
				zombified_piglin = true
				piglin = true
				strider = true
				guardian = true
				magma_cube = true

			[light_sources.settings.entities.swampier_swamps]
				swamp_gas = true
				dragonfly = true

			[light_sources.settings.entities.yungscavebiomes]
				sand_snapper = true
				ice_cube = true

			[light_sources.settings.entities.smallships]
				brigg = true
				galley = true

			[light_sources.settings.entities.immersive_portals]
				nether_portal_new = true
				loading_indicator = true

			[light_sources.settings.entities.darkwaters]
				craeken = true
				aberration = true
				mohast = true
				miraid = true

			[light_sources.settings.entities.naturalist]
				snail = true
				firefly = true
				robin = true
				lizard = true
				deer = true
				boar = true
				butterfly = true
				bear = true
				bass = true
				snake = true
				sparrow = true
				finch = true
				cardinal = true
				duck = true
				elephant = true
				zebra = true
				rattlesnake = true
				rhino = true
				coral_snake = true
				lion = true

			[light_sources.settings.entities.friendsandfoes]
				copper_golem = true
				crab = true
				rascal = true
				mauler = true

			[light_sources.settings.entities.immersive_aircraft]
				biplane = true
				gyrodyne = true

			[light_sources.settings.entities.sleep_tight]
				bed_entity = true

			[light_sources.settings.entities.ecologics]
				squirrel = true

