# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enable entities light source.
	entities = true
	# Enable first-person player light source.
	self = true
	# Enable block entities light source.
	block_entities = true
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				glow_item_frame = false
				player = true
				bat = true
				zombie = true
				creeper = true
				skeleton = true
				cow = true
				sheep = true
				glow_squid = true
				salmon = true
				spider = true
				squid = true
				chicken = true
				cod = true
				enderman = true
				pig = true
				bee = true
				wolf = true
				drowned = true
				item = true
				snowball = true
				boat = true
				zombie_villager = true
				witch = true
				turtle = true
				fox = true
				cave_spider = true
				axolotl = true
				villager = true
				frog = true
				cat = true
				iron_golem = true
				horse = true
				dolphin = true
				tropical_fish = true
				tnt_minecart = true
				chest_minecart = true
				lightning_bolt = true
				slime = true
				experience_orb = true
				pufferfish = true
				donkey = true
				llama = true

			[light_sources.settings.entities.swampier_swamps]
				swamp_gas = true
				dragonfly = true

			[light_sources.settings.entities.yungscavebiomes]
				sand_snapper = true

